### ISSUE TITLE
Moving to JuliaAstro

### ISSUE THREAD

**Issue by cadojo** [JuliaAstro/GeneralAstrodynamics.jl#232]
To: @helgee @giordano

You recently helped me [move](https://github.com/JuliaAstro/EphemerisSources.jl/issues/25) `EphemerisSources.jl` to @JuliaAstro. I would like to do the same for `GeneralAstrodynamics.jl`. By the end of the year, I hope to have this suite of packages published at JOSS. 

I have @JuliaAstro access, so I have just moved this package to the organization. I have not yet updated Julia's General registry to look here. **Is this move okay?** I want to ask permission before adding a somewhat large project to the organization.

**Comment by helgee** [comment]
Hi @cadojo,
no objections from my side with the caveat that I am on an extended hiatus with all things Julia and thus not at all involved with JuliaAstro at the moment.

**Comment by giordano** [comment]
Sorry, I missed this message before, but yes, I have no objections.

**Comment by cadojo** [comment]
Thank you! And thanks for letting me know @helgee, I'll quit tagging you on everything @JuliaAstro then :) @giordano please let me know if there are other astronomy / astrodynamics folks who I should be checking with. If you could make me an admin for JuliaAstro/GeneralAstrodynamics.jl as well, that would be great.
